# Generated by Django 3.2.3 on 2021-06-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_xpd', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
