# Generated by Django 3.2.3 on 2021-06-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage', '0001_initial'),
        ('app_xpd', '0003_managing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Managing',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='member',
            name='position_in_clan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='position_in_clan', to='app_manage.managing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='second_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_position', to='app_manage.managing'),
        ),
        migrations.AddField(
            model_name='user',
            name='position_in_clan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_manage.position'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lineup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manage.lineup'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='app_manage.role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='second_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_role', to='app_manage.role'),
        ),
        migrations.DeleteModel(
            name='Lineup',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
