# Generated by Django 3.2.3 on 2021-06-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage', '0001_initial'),
        ('app_xpd', '0006_auto_20210605_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='managing_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managing_position', to='app_manage.managing'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position_in_clan',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='position_in_clan', to='app_manage.managing'),
        ),
    ]
