# Generated by Django 3.2.3 on 2021-06-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage', '0001_initial'),
        ('app_xpd', '0007_auto_20210605_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position_in_clan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_in_clan', to='app_manage.managing'),
        ),
    ]
