# Generated by Django 3.2.3 on 2021-06-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_xpd', '0009_alter_member_position_in_clan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='in_game_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='in_game_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
